/*
 * Search Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchWriteError
 */
public class SearchWriteErrorTest {
    private final SearchWriteError model = new SearchWriteError();

    /**
     * Model tests for SearchWriteError
     */
    @Test
    public void testSearchWriteError() {
        // TODO: test SearchWriteError
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'documentKeyName'
     */
    @Test
    public void documentKeyNameTest() {
        // TODO: test documentKeyName
    }

    /**
     * Test the property 'documentKeyValue'
     */
    @Test
    public void documentKeyValueTest() {
        // TODO: test documentKeyValue
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
