/*
 * Search Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.SearchParamAttribute;
import org.openapitools.client.model.SearchParamFacet;
import org.openapitools.client.model.SearchParamFilter;
import org.openapitools.client.model.SearchParamSearchable;
import org.openapitools.client.model.SearchParamSort;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchParams
 */
public class SearchParamsTest {
    private final SearchParams model = new SearchParams();

    /**
     * Model tests for SearchParams
     */
    @Test
    public void testSearchParams() {
        // TODO: test SearchParams
    }

    /**
     * Test the property 'offset'
     */
    @Test
    public void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'term'
     */
    @Test
    public void termTest() {
        // TODO: test term
    }

    /**
     * Test the property 'searchables'
     */
    @Test
    public void searchablesTest() {
        // TODO: test searchables
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'facets'
     */
    @Test
    public void facetsTest() {
        // TODO: test facets
    }

    /**
     * Test the property 'sorts'
     */
    @Test
    public void sortsTest() {
        // TODO: test sorts
    }

    /**
     * Test the property 'minScore'
     */
    @Test
    public void minScoreTest() {
        // TODO: test minScore
    }

}
