/*
 * Search Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.SearchConfigSchemaAttribute;
import org.openapitools.client.model.SearchConfigSchemaFacet;
import org.openapitools.client.model.SearchConfigSchemaFilter;
import org.openapitools.client.model.SearchConfigSchemaSearchable;
import org.openapitools.client.model.SearchConfigSchemaSortable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchConfigSchema
 */
public class SearchConfigSchemaTest {
    private final SearchConfigSchema model = new SearchConfigSchema();

    /**
     * Model tests for SearchConfigSchema
     */
    @Test
    public void testSearchConfigSchema() {
        // TODO: test SearchConfigSchema
    }

    /**
     * Test the property 'index'
     */
    @Test
    public void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'documentKeyName'
     */
    @Test
    public void documentKeyNameTest() {
        // TODO: test documentKeyName
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'searchables'
     */
    @Test
    public void searchablesTest() {
        // TODO: test searchables
    }

    /**
     * Test the property 'facets'
     */
    @Test
    public void facetsTest() {
        // TODO: test facets
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

    /**
     * Test the property 'sortables'
     */
    @Test
    public void sortablesTest() {
        // TODO: test sortables
    }

}
