/*
 * Search Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.SearchConfigSchemaAttribute;
import org.openapitools.client.model.SearchConfigSchemaFacet;
import org.openapitools.client.model.SearchConfigSchemaFilter;
import org.openapitools.client.model.SearchConfigSchemaSearchable;
import org.openapitools.client.model.SearchConfigSchemaSortable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce.Search.JSON;

/**
 * contains index configurations fields
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-28T11:12:56.191245973Z[Etc/UTC]", comments = "Generator version: 7.9.0")
public class SearchConfigSchema {
  public static final String SERIALIZED_NAME_INDEX = "index";
  @SerializedName(SERIALIZED_NAME_INDEX)
  private String index;

  public static final String SERIALIZED_NAME_DOCUMENT_KEY_NAME = "documentKeyName";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_KEY_NAME)
  private String documentKeyName;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private List<SearchConfigSchemaAttribute> attributes = new ArrayList<>();

  public static final String SERIALIZED_NAME_SEARCHABLES = "searchables";
  @SerializedName(SERIALIZED_NAME_SEARCHABLES)
  private List<SearchConfigSchemaSearchable> searchables = new ArrayList<>();

  public static final String SERIALIZED_NAME_FACETS = "facets";
  @SerializedName(SERIALIZED_NAME_FACETS)
  private List<SearchConfigSchemaFacet> facets = new ArrayList<>();

  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  private List<SearchConfigSchemaFilter> filters = new ArrayList<>();

  public static final String SERIALIZED_NAME_SORTABLES = "sortables";
  @SerializedName(SERIALIZED_NAME_SORTABLES)
  private List<SearchConfigSchemaSortable> sortables = new ArrayList<>();

  public SearchConfigSchema() {
  }

  public SearchConfigSchema index(String index) {
    this.index = index;
    return this;
  }

  /**
   * index name, to create or where update configuration
   * @return index
   */
  @javax.annotation.Nonnull
  public String getIndex() {
    return index;
  }

  public void setIndex(String index) {
    this.index = index;
  }


  public SearchConfigSchema documentKeyName(String documentKeyName) {
    this.documentKeyName = documentKeyName;
    return this;
  }

  /**
   * field which value will be used as document id [#DOCGENBUG REQUIRED FIELD]
   * @return documentKeyName
   */
  @javax.annotation.Nullable
  public String getDocumentKeyName() {
    return documentKeyName;
  }

  public void setDocumentKeyName(String documentKeyName) {
    this.documentKeyName = documentKeyName;
  }


  public SearchConfigSchema attributes(List<SearchConfigSchemaAttribute> attributes) {
    this.attributes = attributes;
    return this;
  }

  public SearchConfigSchema addAttributesItem(SearchConfigSchemaAttribute attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

  /**
   * fields that can be stored into index and later retrieved
   * @return attributes
   */
  @javax.annotation.Nonnull
  public List<SearchConfigSchemaAttribute> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<SearchConfigSchemaAttribute> attributes) {
    this.attributes = attributes;
  }


  public SearchConfigSchema searchables(List<SearchConfigSchemaSearchable> searchables) {
    this.searchables = searchables;
    return this;
  }

  public SearchConfigSchema addSearchablesItem(SearchConfigSchemaSearchable searchablesItem) {
    if (this.searchables == null) {
      this.searchables = new ArrayList<>();
    }
    this.searchables.add(searchablesItem);
    return this;
  }

  /**
   * fields that can be used for fulltext searches
   * @return searchables
   */
  @javax.annotation.Nullable
  public List<SearchConfigSchemaSearchable> getSearchables() {
    return searchables;
  }

  public void setSearchables(List<SearchConfigSchemaSearchable> searchables) {
    this.searchables = searchables;
  }


  public SearchConfigSchema facets(List<SearchConfigSchemaFacet> facets) {
    this.facets = facets;
    return this;
  }

  public SearchConfigSchema addFacetsItem(SearchConfigSchemaFacet facetsItem) {
    if (this.facets == null) {
      this.facets = new ArrayList<>();
    }
    this.facets.add(facetsItem);
    return this;
  }

  /**
   * fields that can be used for aggregations
   * @return facets
   */
  @javax.annotation.Nullable
  public List<SearchConfigSchemaFacet> getFacets() {
    return facets;
  }

  public void setFacets(List<SearchConfigSchemaFacet> facets) {
    this.facets = facets;
  }


  public SearchConfigSchema filters(List<SearchConfigSchemaFilter> filters) {
    this.filters = filters;
    return this;
  }

  public SearchConfigSchema addFiltersItem(SearchConfigSchemaFilter filtersItem) {
    if (this.filters == null) {
      this.filters = new ArrayList<>();
    }
    this.filters.add(filtersItem);
    return this;
  }

  /**
   * fields that can be used for filtering
   * @return filters
   */
  @javax.annotation.Nullable
  public List<SearchConfigSchemaFilter> getFilters() {
    return filters;
  }

  public void setFilters(List<SearchConfigSchemaFilter> filters) {
    this.filters = filters;
  }


  public SearchConfigSchema sortables(List<SearchConfigSchemaSortable> sortables) {
    this.sortables = sortables;
    return this;
  }

  public SearchConfigSchema addSortablesItem(SearchConfigSchemaSortable sortablesItem) {
    if (this.sortables == null) {
      this.sortables = new ArrayList<>();
    }
    this.sortables.add(sortablesItem);
    return this;
  }

  /**
   * fields that can be used for sorting
   * @return sortables
   */
  @javax.annotation.Nullable
  public List<SearchConfigSchemaSortable> getSortables() {
    return sortables;
  }

  public void setSortables(List<SearchConfigSchemaSortable> sortables) {
    this.sortables = sortables;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SearchConfigSchema instance itself
   */
  public SearchConfigSchema putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchConfigSchema searchConfigSchema = (SearchConfigSchema) o;
    return Objects.equals(this.index, searchConfigSchema.index) &&
        Objects.equals(this.documentKeyName, searchConfigSchema.documentKeyName) &&
        Objects.equals(this.attributes, searchConfigSchema.attributes) &&
        Objects.equals(this.searchables, searchConfigSchema.searchables) &&
        Objects.equals(this.facets, searchConfigSchema.facets) &&
        Objects.equals(this.filters, searchConfigSchema.filters) &&
        Objects.equals(this.sortables, searchConfigSchema.sortables)&&
        Objects.equals(this.additionalProperties, searchConfigSchema.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, documentKeyName, attributes, searchables, facets, filters, sortables, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchConfigSchema {\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    documentKeyName: ").append(toIndentedString(documentKeyName)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    searchables: ").append(toIndentedString(searchables)).append("\n");
    sb.append("    facets: ").append(toIndentedString(facets)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    sortables: ").append(toIndentedString(sortables)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("index");
    openapiFields.add("documentKeyName");
    openapiFields.add("attributes");
    openapiFields.add("searchables");
    openapiFields.add("facets");
    openapiFields.add("filters");
    openapiFields.add("sortables");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("index");
    openapiRequiredFields.add("attributes");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SearchConfigSchema
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SearchConfigSchema.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SearchConfigSchema is not found in the empty JSON string", SearchConfigSchema.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SearchConfigSchema.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("index").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `index` to be a primitive type in the JSON string but got `%s`", jsonObj.get("index").toString()));
      }
      if ((jsonObj.get("documentKeyName") != null && !jsonObj.get("documentKeyName").isJsonNull()) && !jsonObj.get("documentKeyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `documentKeyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("documentKeyName").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("attributes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `attributes` to be an array in the JSON string but got `%s`", jsonObj.get("attributes").toString()));
      }

      JsonArray jsonArrayattributes = jsonObj.getAsJsonArray("attributes");
      // validate the required field `attributes` (array)
      for (int i = 0; i < jsonArrayattributes.size(); i++) {
        SearchConfigSchemaAttribute.validateJsonElement(jsonArrayattributes.get(i));
      };
      if (jsonObj.get("searchables") != null && !jsonObj.get("searchables").isJsonNull()) {
        JsonArray jsonArraysearchables = jsonObj.getAsJsonArray("searchables");
        if (jsonArraysearchables != null) {
          // ensure the json data is an array
          if (!jsonObj.get("searchables").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `searchables` to be an array in the JSON string but got `%s`", jsonObj.get("searchables").toString()));
          }

          // validate the optional field `searchables` (array)
          for (int i = 0; i < jsonArraysearchables.size(); i++) {
            SearchConfigSchemaSearchable.validateJsonElement(jsonArraysearchables.get(i));
          };
        }
      }
      if (jsonObj.get("facets") != null && !jsonObj.get("facets").isJsonNull()) {
        JsonArray jsonArrayfacets = jsonObj.getAsJsonArray("facets");
        if (jsonArrayfacets != null) {
          // ensure the json data is an array
          if (!jsonObj.get("facets").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `facets` to be an array in the JSON string but got `%s`", jsonObj.get("facets").toString()));
          }

          // validate the optional field `facets` (array)
          for (int i = 0; i < jsonArrayfacets.size(); i++) {
            SearchConfigSchemaFacet.validateJsonElement(jsonArrayfacets.get(i));
          };
        }
      }
      if (jsonObj.get("filters") != null && !jsonObj.get("filters").isJsonNull()) {
        JsonArray jsonArrayfilters = jsonObj.getAsJsonArray("filters");
        if (jsonArrayfilters != null) {
          // ensure the json data is an array
          if (!jsonObj.get("filters").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `filters` to be an array in the JSON string but got `%s`", jsonObj.get("filters").toString()));
          }

          // validate the optional field `filters` (array)
          for (int i = 0; i < jsonArrayfilters.size(); i++) {
            SearchConfigSchemaFilter.validateJsonElement(jsonArrayfilters.get(i));
          };
        }
      }
      if (jsonObj.get("sortables") != null && !jsonObj.get("sortables").isJsonNull()) {
        JsonArray jsonArraysortables = jsonObj.getAsJsonArray("sortables");
        if (jsonArraysortables != null) {
          // ensure the json data is an array
          if (!jsonObj.get("sortables").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `sortables` to be an array in the JSON string but got `%s`", jsonObj.get("sortables").toString()));
          }

          // validate the optional field `sortables` (array)
          for (int i = 0; i < jsonArraysortables.size(); i++) {
            SearchConfigSchemaSortable.validateJsonElement(jsonArraysortables.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SearchConfigSchema.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SearchConfigSchema' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SearchConfigSchema> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SearchConfigSchema.class));

       return (TypeAdapter<T>) new TypeAdapter<SearchConfigSchema>() {
           @Override
           public void write(JsonWriter out, SearchConfigSchema value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SearchConfigSchema read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             SearchConfigSchema instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SearchConfigSchema given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SearchConfigSchema
   * @throws IOException if the JSON string is invalid with respect to SearchConfigSchema
   */
  public static SearchConfigSchema fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SearchConfigSchema.class);
  }

  /**
   * Convert an instance of SearchConfigSchema to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

